// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
// app/layout.tsx
import './globals.css';
import { AuthProvider } from '@/context/AuthProvider';

export const metadata = {
  title: 'Recipe Generator',
  description: 'AI Recipe Generator',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[url('/chocolate-4455840_1280.jpg')] bg-cover bg-center bg-no-repeat text-white">
        <AuthProvider>
          <main className="min-h-screen flex items-center justify-center p-6">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}

